# Generated by Django 4.0.6 on 2022-07-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
